kind: pipeline
name: default

steps:
  - name: frontend
    image: node:10.16.0
    commands:
      - cd frontend
      - npm install
      - npm test
      - npm run build
  - name: backend
    image: maven:3-jdk-8
    commands:
      - cd backend
      - mvn package -B