kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules
        - /root/.m2/repository
        - /drone/.m2

  #  - name: frontend
  #    image: node:10.16.0
  #    commands:
  #      - cd frontend
  #      - npm install
  #      - npm test
  #      - npm run build

  - name: backend
    image: maven:3-jdk-11
    #    environment:
    #      M2_HOME: ./backend/.m2
    #      MAVEN_HOME: ./backend/.m2
    commands:
      - cd backend
      #      - mvn help:evaluate -Dexpression=settings.localRepository | grep -v '\[INFO\]'
      - mvn package -B -Dmaven.repo.local=/drone/.m2/repository

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules
        - /root/.m2/repository
        - /drone/.m2

volumes:
  - name: cache
    host:
      path: /tmp/cache
