kind: pipeline
name: default

steps:
  - name: frontend
    image: node
    commands:
      - cd frontend
      - npm install
      - npm test
  - name: backend
    image: maven:3-jdk-8
    commands:
      - cd backend
      - mvn package -B