kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules
        - /drone/.m2

  - name: frontend
    image: node:10.16.0
    commands:
      - cd frontend
      - npm install
      - npm test
  #      - npm run build

  - name: backend
    image: maven:3-jdk-11
    environment:
      M2_HOME: /drone/.m2
      MAVEN_HOME: /drone/.m2
    commands:
      - cd backend
      - mvn package -B

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules
        - /drone/.m2

volumes:
  - name: cache
    host:
      path: /tmp/cache
