kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    commands:
      - cd frontend
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: frontend
    image: node:10.16.0
    commands:
      - cd frontend
      - npm install
      - npm test
      - npm run build

  - name: backend
    image: maven:3-jdk-11
    commands:
      - cd backend
      - mvn package -B

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    commands:
      - cd frontend
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache