kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules
        - ./backend/.m2/repository

  - name: frontend
    image: node:10.16.0
    commands:
  #      - cd frontend
  #      - npm install
  #      - npm test
  #      - npm run build

  - name: backend
    image: maven:3-jdk-11
    commands:
  #      - cd backend
  #      - mvn test
  #      - mvn help:evaluate -Dexpression=settings.localRepository | grep -v '\[INFO\]'
  #      - mvn package -B -Dmaven.repo.local=.m2/repository


  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules
        - ./backend/.m2/repository


  - name: build images
    image: tiangolo/docker-with-compose
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - docker-compose build
      - docker-compose push
    when:
      branch:
        - master


volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock



