image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
#  - build
  - test
#  - deploy

maven-test:
  image: maven:3-jdk-8
  stage: build
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

#maven-build:
#  image: maven:3-jdk-8
#  stage: build
#  script: "mvn package -B"
#  artifacts:
#    paths:
#      - target/*.jar

#build:
#  stage: build
#  script: ./gradlew build
#  artifacts:
#    paths:
#      - build/libs/myApp-4.0.0-SNAPSHOT.jar
#
#unitTests:
#  stage: test
#  script:
#    - ./gradlew test
#docker-build:
#  stage: package
#  script:
#    - docker build -t registry.gitlab.com/reryk/linkzone .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/reryk/linkzone