version: "3"
services:
  linkzone-frontend:
    container_name: linkzone-frontend-container
    image: reryk/linkzone-frontend
    build: ./frontend
    restart: always
    networks:
      - web
    expose:
      - 80

  linkzone-database:
    container_name: linkzone-database-container
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - /opt/mysql1:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_DATABASE: linkzone
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306

  linkzone-backend:
    container_name: linkzone-backend-container
    image: reryk/linkzone-backend
    build: ./backend
    restart: always
    networks:
      - web
      - internal
    volumes:
      - ~/.m2:/root/.m2
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://linkzone-database:3306/linkzone?useSSL=false
    depends_on:
      - linkzone-database

networks:
  web:
    external: true
  internal:
    external: false