version: "3"
services:
  database:
    container_name: linkzone-database-service
    image: mysql/mysql-server:5.7
    volumes:
      - /opt/mysql1:/var/lib/mysql
    environment:
      MYSQL_DATABASE: linkzone
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306

  backend:
    image: linkzone-backend-service:latest
    container_name: linkzone-backend-service
    build: ./backend
    volumes:
      - ~/.m2:/root/.m2
    expose:
      - 8080
    ports:
      - 9001:8080
    depends_on:
      - database
    links:
      - database

  frontend:
    image: linkzone-frontend-service:latest
    container_name: linkzone-frontend-service
    build: ./frontend
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 9000:80
    restart: always
    depends_on:
      - backend
    links:
      - backend