version: "3"
services:
  linkzone-frontend:
    build: ./frontend
    image: linkzone-frontend
    container_name: linkzone-frontend-container
    restart: always
    environment:
      - PROXY_TARGET=http://linkzone-backend-container:8080
    ports:
      - 8080:80
      - 3001:3000
    depends_on:
      - linkzone-backend

  linkzone-backend:
    build: ./backend
    image: linkzone-backend
    container_name: linkzone-backend-container
    restart: always
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - 8081:8080
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://linkzone-database:3306/linkzone?useSSL=false
      - SERVER_PORT=8080
    depends_on:
      - linkzone-database

  linkzone-database:
    image: mysql/mysql-server:5.7
    container_name: linkzone-database-container
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: linkzone
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    expose:
      - 3306


volumes:
  db_data: {}