version: "3"
services:
  linkzone-database:
    image: mysql/mysql-server:8.0
    container_name: linkzone-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=linkzone
      - MYSQL_USER=linkzone
      - MYSQL_PASSWORD=linkzone
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - linkzone_db:/var/lib/mysql
    expose:
      - 3306
    ports:
      - '3306:3306'

volumes:
  linkzone_db:
    external: true