security:
  jwt:
    secret: secret
    expirationInMs: 604800000

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 3MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/linkzone?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

amazonProperties:
  endpointUrl: ${S3_ENDPOINT_URL}
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  bucketName: ${S3_BUCKET_NAME}
  region: ${S3_REGION}

server.port: 8080
