security:
  jwt:
    secret: JWTSuperSec21312dasretKey
    expirationInMs: 604800000

file:
  upload-dir: ./public/static

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 3MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/linkzone?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

amazonProperties:
  endpointUrl: https://linkzone.s3.eu-central-1.amazonaws.com
  accessKey: AKIAVWGJK2SMRSUKFRVQ
  secretKey: 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
  bucketName: linkzone
  region: eu-central-1

server.port: 8080
