name: Push Docker Image

on:
  push:
    branches: [ dev ]

env:
  NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Deploy
        run: mvn deploy -X --errors