name: Push Docker Image

on:
  push:
    branches: [ dev ]


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Run the Maven verify phase
        run: mvn -v && echo $JAVA_HOME && mvn --batch-mode verify