name: Release

#on:
#  workflow_dispatch

on:
  push:
    branches: [ dev ]

env:
  #  NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Release
        run: mvn --batch-mode --errors release:prepare release:perform
        env:
          GITHUB_USERNAME: erykio
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
