name: Release

on:
  workflow_dispatch

env:
  #  NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  NEXUS_USER: ${{ secrets.NEXUS_USER }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Prepare release
        run: mvn --batch-mode --errors release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read SCM tag
        id: scm_tag
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'release.properties'
          property: 'scm.tag'

      - name: Print a new tag
        run: echo ${{ steps.scm_tag.outputs.value }}

      - name: Perform release
        run: mvn --batch-mode --errors release:perform

      - name: Create Github Release
        run: echo "get ID of created tag and create a release for it"